# ----------------------------------------------------------
# Basic Site Settings
# ----------------------------------------------------------
title: "Prahalad Atreyaa"
description: "A simplified yet classic personal website using Jekyll + Minimal Mistakes"
# If your repository is named <username>.github.io, set:
url: "https://prahaladatreyaa.github.io"
baseurl: ""
# If your site is hosted at https://<username>.github.io/my-site, set:
# url: "https://<username>.github.io"
# baseurl: "/my-site"

# ----------------------------------------------------------
# Theme Settings
# ----------------------------------------------------------
# This is the key to using Minimal Mistakes as a remote theme:
remote_theme: "mmistakes/minimal-mistakes"

# # Build plugins (GitHub Pages + others)
# Required plugin for remote themes:
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache   # <--- IMPORTANT for 'include_cached' used by Minimal Mistakes


# Choose a built-in Minimal Mistakes skin. Options include:
# "default", "dark", "solarized", "air", "contrast", "neon", etc.
minimal_mistakes_skin: "default"

# If you'd like to use the "excerpt_separator" for post previews
# excerpt_separator: "<!--more-->"

# ----------------------------------------------------------
# Site Author Details
# ----------------------------------------------------------
author:
  name: "Prahalad Atreyaa"
  avatar: "/assets/images/prahalad_dp.jpg"
  bio: "SDE 3 who has 5.5 + years (including internships) in back end software development & research roles. Predominantly in Java (Spring boot), Python (flask), & Javascript based technical stack/ frameworks."
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/prahaladatreyaa"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/prahaladatreyaaa/"\
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=EzpQM1sAAAAJ&hl=en"
    # Add more links (Twitter, Google Scholar, etc.) as desired

# -------------------------------------------------------
# Header Navigation (Top Nav Bar)
# -------------------------------------------------------
# This ensures About and Research appear at the top of every page that uses
# a default Minimal Mistakes layout with the masthead.
# header:
#   nav:
#     - title: "Home"
#       url: /
#     - title: "About"
#       url: /about/
#     - title: "Research"
#       url: /research/

# # Navigation
# nav:
#   - name:           "home"
#     href:           "/"
#   - name:           "about"
#     href:           "/about/"
#   - name:           "publications"
#     href:           "/publication"
#   - name:           "people"
#     href:           "/people"
#   - name:           "blog"
#     href:           "/blog"

# If you don't want to show the site title in the header, you can do:
# masthead:
#   title: true


# If you prefer a separate file, you can place the nav in _data/navigation.yml

# ----------------------------------------------------------
# Default Layouts and Author Profile
# ----------------------------------------------------------
# Defaults so pages/posts use single layout and show author profile
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
