title: "Prahalad Atreyaa Ashok"
description: "A personal site using Minimal Mistake"
baseurl: "" # If using <username>.github.io repo, keep this empty
url: "https://prahaladatreyaa.github.io" # change to your actual GitHub Pages URL
theme: minimal-mistakes-jekyll
include:
  - "_images"
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation setup (optional)
navigation:
  main:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default"
author:
  name: "Prahalad Atreyaa"
  avatar: "/assets/images/PP.png"
  bio: "SDE 3 who has 5.5 + years (including internships) in back end software development & research roles. Predominantly in Java (Spring boot), Python (flask), & Javascript based technical stack/ frameworks."
